import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='keywords' content='next.js
        hunting coders'/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<nav className={styles.mainnav}>
        <ul>
        <Link href="/"><li>Home</li></Link>
        <Link href="/About"><li>About</li></Link>
        <Link href="/Contact"><li>Contact</li></Link>
        <Link href="/Blogs"><li>Blogs</li></Link>
        </ul>
      </nav>*/}
      <Script src='/Testing.js' strategy='lazyOnload'></Script>
      {/*{LazyOnload means it will run the script when the page is loaded  }*/}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Hunting Coders!</a>
        </h1>
        <p className={styles.description}>
          Scam Hai Bhai{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      <div className='blogs'>
      <h1>POPULAR BLOGS</h1>
        <div className='blogItems'>
          <h3>How To Learn JavaScript In 2022</h3>
          <p> Faltu Hai !! Chala Ja</p>
        </div>
        <div className='blogItems'>
          <h3>How To Learn JavaScript In 2022</h3>
          <p> Faltu Hai !! Chala Ja</p>
        </div>
        <div className='blogItems'>
          <h3>How To Learn JavaScript In 2022</h3>
          <p> Faltu Hai !! Chala Ja</p>
        </div>
        <div className='blogItems'>
          <h3>How To Learn JavaScript In 2022</h3>
          <p> Faltu Hai !! Chala Ja</p>
        </div>
      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


// The Endit